# Generated by Django 3.2.18 on 2023-05-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='user',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('족발,보쌈', '족발,보쌈'), ('찜,탕,찌개', '찜,탕,찌개'), ('돈까스,회,일식', '돈까스,회,일식'), ('피자', '피자'), ('고기,구이', '고기,구이'), ('야식', '야식'), ('양식', '양식'), ('치킨', '치킨'), ('중식', '중식'), ('아시안', '아시안'), ('백반,죽,국수', '백반,죽,국수'), ('도시락', '도시락'), ('분식', '분식'), ('카페,디저트', '카페,디저트'), ('패스트푸드', '패스트푸드'), ('기타', '기타')], max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='region',
            field=models.CharField(choices=[('서울', '서울특별시'), ('부산', '부산광역시'), ('대구', '대구광역시'), ('인천', '인천광역시'), ('광주', '광주광역시'), ('대전', '대전광역시'), ('울산', '울산광역시'), ('세종', '세종특별자치시'), ('경기도', '경기도'), ('강원도', '강원도'), ('충청북도', '충청북도'), ('충청남도', '충청남도'), ('전라북도', '전라북도'), ('전라남도', '전라남도'), ('경상북도', '경상북도'), ('경상남도', '경상남도'), ('제주도', '제주특별자치도')], max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='time_lastorder',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
