# Generated by Django 3.2.18 on 2023-04-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
