# Generated by Django 3.2.18 on 2023-05-03 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='first_review',
        ),
    ]
