# Generated by Django 3.2.18 on 2023-05-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_restaurant_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
