# Generated by Django 3.2.18 on 2023-05-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20230503_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
