# Generated by Django 3.2.18 on 2023-05-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_remove_restaurant_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
