# Generated by Django 3.2.18 on 2023-05-03 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_restaurant_image_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='image_thumbnail',
            new_name='image_first',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='first_photo',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='first_review',
        ),
    ]
