# Generated by Django 3.2.18 on 2023-05-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clndr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='date',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
