# Generated by Django 3.2.18 on 2023-05-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clndr', '0002_meet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='date',
            field=models.DateField(),
        ),
    ]
