# Generated by Django 3.2.18 on 2023-05-07 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clndr', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='review',
            new_name='meet',
        ),
    ]
